#!/bin/sh

cd "$(dirname "$0")" || exit 1
# make sure to run ./runme, script from https://git.sr.ht/~jasom/nix-lisp-dev
all() {
    # build_env
    ensure_quicklisp
}

server() {
    nix-build '<nixpkgs>' -A inotify-tools -o inotify-tools
    ./inotify-tools/bin/inotifywait  -m -e move_self -e delete_self -e modify -e close_write default.nix | \
        while read -r; do build_env; done
}

# build_env() {
#     nix-build . -A env
# }

ensure_quicklisp() {
    if ! test -f quicklisp/setup.lisp; then
        curl https://beta.quicklisp.org/quicklisp.lisp > quicklisp.lisp
        result/bin/sbcl --no-sysinit --no-userinit --load quicklisp.lisp --eval '(quicklisp-quickstart:install :path #P"./quicklisp/")'  --eval '(quit)'
    fi
    test -f config/sbcl-init.lisp || touch config/sbcl-init.lisp
}


"${1:-all}"
